"""
Extract Rift Wizard 3 spell / equipment / component data into a JSON file
for the static browser resource. Reads ONLY from the game install dir;
writes only into this project's site/ folder.
"""
import os, sys, json, ast, inspect, textwrap, re

os.environ['SDL_VIDEODRIVER'] = 'dummy'
os.environ['SDL_AUDIODRIVER'] = 'dummy'

GAME = r"E:\SteamLibrary\steamapps\common\Rift Wizard 3"
HERE = os.path.dirname(os.path.abspath(__file__))

import ids as ids_mod  # stable append-only id assignment (HERE-relative; safe before chdir)
OUT_DIR = os.path.join(HERE, "site")
os.makedirs(OUT_DIR, exist_ok=True)

sys.path.insert(0, GAME)
os.chdir(GAME)  # so rl_data/loc text json loads

# Import order matters (circular imports): Equipment pulls Level/CommonContent/Monsters/Spells/Components.
import Equipment
import Spells
import Components
import text
from Level import (resolve_text, Tags, attr_colors, format_attr, tag_key, attr_key,
                   tag_label, Spell, Equipment as EquipmentBase, Component as ComponentBase,
                   Buff as BuffBase, stat_names)

# ---------------------------------------------------------------------------
# Color map: replicate RiftWizard3.tooltip_colors without importing the UI.
# ---------------------------------------------------------------------------
def to_tup(c):
    return [c.r, c.g, c.b]

COLOR_DAMAGE = type(Tags.Fire.color)(215, 0, 0)
Color = type(Tags.Fire.color)

tooltip_colors = {}
for tag in Tags:
    tooltip_colors[tag.name.lower()] = to_tup(tag.color)
for k, v in attr_colors.items():
    tooltip_colors[k] = to_tup(v)
tooltip_colors['default'] = [255, 255, 255]

# manual additions mirrored from RiftWizard3.py
_manual = {
    'petrify': Tags.Construct, 'petrified': Tags.Construct, 'petrifies': Tags.Construct,
    'frozen': Tags.Ice, 'freezes': Tags.Ice, 'freeze': Tags.Ice,
    'stunned': Tags.Physical, 'stun': Tags.Physical, 'stuns': Tags.Physical,
    'poisoned': Tags.Poison, 'poisons': Tags.Poison,
    'glassify': Tags.Glass, 'glassified': Tags.Glass, 'glassed': Tags.Glass,
    'sleep': Tags.Arcane, 'sleeps': Tags.Arcane,
    'silence': Tags.Arcane, 'silenced': Tags.Arcane, 'silences': Tags.Arcane,
    'necrosis': Tags.Dark, 'fear': Tags.Dark, 'fears': Tags.Dark, 'feared': Tags.Dark,
    'blind': Tags.Eye, 'blinds': Tags.Eye, 'blinded': Tags.Eye,
    'bleed': Tags.Blood, 'bleeds': Tags.Blood, 'bleeding': Tags.Blood, 'hemorrhage': Tags.Blood,
    'requires_los': Tags.Translocation, 'ally': Tags.Conjuration, 'hp_cost': Tags.Blood,
}
for k, tg in _manual.items():
    tooltip_colors[k] = to_tup(tg.color)
tooltip_colors['berserk'] = to_tup(COLOR_DAMAGE)
tooltip_colors['berserked'] = to_tup(COLOR_DAMAGE)
tooltip_colors['berserks'] = to_tup(COLOR_DAMAGE)
tooltip_colors['enemy'] = to_tup(COLOR_DAMAGE)
tooltip_colors['wizard'] = [2, 136, 209]
tooltip_colors['quick_cast'] = [255, 255, 255]
tooltip_colors['max_channel'] = [153, 51, 102]

# ---------------------------------------------------------------------------
# Slots
# ---------------------------------------------------------------------------
SLOT_NAMES = {0: "Trinket", 1: "Head", 2: "Body", 3: "Feet", 4: "Weapon"}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def rtext(value, fmt=None):
    try:
        return resolve_text(value, fmt=fmt)
    except Exception as e:
        return ""

def asset_filename(get_asset_result):
    # last element + .png, lowercased for the web
    return (get_asset_result[-1] + ".png").lower()

# --- sprite sheet dimensions (for pure-CSS idle animation) ------------------
# Read PNG width/height straight from the IHDR header — no image library needed
# (avoids an SDL/pygame DLL conflict when cwd is the game dir).
import struct
_CHAR_DIR = os.path.join(GAME, "rl_data", "char")
_char_index = None
def _char_path(icon):
    global _char_index
    if _char_index is None:
        _char_index = {}
        for fn in os.listdir(_CHAR_DIR):
            if fn.lower().endswith(".png"):
                _char_index[fn.lower()] = os.path.join(_CHAR_DIR, fn)
    return _char_index.get(icon.lower())

def _png_size(path):
    with open(path, "rb") as f:
        head = f.read(24)
    if len(head) < 24 or head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return struct.unpack(">II", head[16:24])   # width, height

def sheet_grid(icon, radius):
    """(columns, rows) of a char spritesheet; idle = last row, cols = idle frames."""
    p = _char_path(icon)
    if not p:
        return (1, 1)
    try:
        w, h = _png_size(p)
    except Exception:
        return (1, 1)
    base = 60 if w % 60 == 0 else 16
    fs = base * (1 + 2 * (radius or 0))
    if fs <= 0 or w % fs or h % fs:
        return (1, 1)
    return (w // fs, h // fs)

def render_bonus_lines(o):
    """Replicate the autogenerated bonus tooltip lines for an equipment/buff."""
    lines = []
    for tag, bonuses in o.tag_bonuses_pct.items():
        for attr, val in bonuses.items():
            lines.append(rtext((text.TAG_PCT_BONUS, {
                "tag_label": tag_label(tag), "tag_key": tag_key(tag),
                "val": int(val), "attr_label": format_attr(attr), "attr_key": attr_key(attr)})))
    for tag, bonuses in o.tag_bonuses.items():
        for attr, val in bonuses.items():
            lines.append(rtext((text.TAG_VAL_BONUS, {
                "tag_label": tag_label(tag), "tag_key": tag_key(tag),
                "val": int(val), "attr_label": format_attr(attr), "attr_key": attr_key(attr)})))
    for attr, val in o.global_bonuses_pct.items():
        tmpl = text.ALL_GAIN_PCT if val >= 0 else text.ALL_LOSE_PCT
        lines.append(rtext((tmpl, {"val": int(val), "attr_label": format_attr(attr), "attr_key": attr_key(attr)})))
    for attr, val in o.global_bonuses.items():
        tmpl = text.ALL_GAIN_VAL if val >= 0 else text.ALL_LOSE_VAL
        lines.append(rtext((tmpl, {"val": int(val), "attr_label": format_attr(attr), "attr_key": attr_key(attr)})))
    for tag, val in o.resists.items():
        if val:
            lines.append(rtext((text.RESIST_VAL, {"val": val, "tag_label": tag_label(tag)})))
    return [l for l in lines if l]

# Mirror of RiftWizard3.tt_attrs, in the game's own order (the UI module isn't
# importable in the build env — no steamworks — same reason tooltip_colors are
# mirrored, §2). This is the game's canonical attribute list: it's what the
# spell examine "Attributes:" section iterates, and the only new_attributes an
# upgrade tooltip surfaces as a text line. Keep it a tuple (order matters for
# spell stat-line display) — `in` membership checks still work.
TT_ATTRS = (
    'num_targets', 'damage', 'duration', 'radius', 'shields', 'shot_cooldown',
    'strikechance', 'cooldown', 'max_channel', 'num_summons', 'minion_health',
    'minion_damage', 'minion_duration', 'minion_range',
)

def upgrade_bonus_lines(u):
    """Replicate the game's auto-generated upgrade tooltip lines — the stat
    deltas the examine panel draws above an upgrade's prose. Pure-stat upgrades
    (e.g. Relentless Cascade: +2 range/+3 charges) have NO prose at all, so
    without these they render blank. Order mirrors RiftWizard3.draw_examine's
    upgrade branch; the colored-vs-plain choice keys off tooltip_colors exactly
    as the game does (attr names are never tag/status keys, so spell/global stat
    lines come out plain — matching the game)."""
    lines = []
    def add(tmpl, **kw): lines.append(rtext((tmpl, kw)))
    for tag, bonuses in u.tag_bonuses_pct.items():
        for attr, val in bonuses.items():
            add(text.TAG_PCT_BONUS, tag_label=tag_label(tag), tag_key=tag_key(tag),
                val=int(val), attr_label=format_attr(attr), attr_key=attr_key(attr))
    for tag, bonuses in u.tag_bonuses.items():
        for attr, val in bonuses.items():
            add(text.TAG_VAL_BONUS, tag_label=tag_label(tag), tag_key=tag_key(tag),
                val=int(val), attr_label=format_attr(attr), attr_key=attr_key(attr))
    # Per-spell bonuses: the game only shows attrs the target spell actually has.
    for spell, bonuses in u.spell_bonuses_pct.items():
        sp = spell()
        for attr, val in bonuses.items():
            if attr not in sp.stats: continue
            tmpl = text.GAIN_PCT_COLORED if attr in tooltip_colors else text.GAIN_PCT_PLAIN
            add(tmpl, name=sp.name, val=val, attr_label=format_attr(attr), attr_key=attr_key(attr))
    for spell, bonuses in u.spell_bonuses.items():
        sp = spell()
        for attr, val in bonuses.items():
            if attr not in sp.stats: continue
            tmpl = text.GAIN_VAL_COLORED if attr in tooltip_colors else text.GAIN_VAL_PLAIN
            add(tmpl, name=sp.name, val=val, attr_label=format_attr(attr), attr_key=attr_key(attr))
    prereq = getattr(u, 'prereq', None)
    if prereq is not None:
        for attr, val in getattr(u, 'new_attributes', {}).items():
            if attr in TT_ATTRS or attr == 'hp_cost':  # game always colors these
                add(text.GAIN_VAL_COLORED, name=prereq.name, val=val,
                    attr_label=format_attr(attr), attr_key=attr_key(attr))
    for attr, val in u.global_bonuses_pct.items():
        tmpl = text.ALL_GAIN_PCT if val >= 0 else text.ALL_LOSE_PCT
        add(tmpl, val=int(val), attr_label=format_attr(attr), attr_key=attr_key(attr))
    for attr, val in u.global_bonuses.items():
        tmpl = text.ALL_GAIN_VAL if val >= 0 else text.ALL_LOSE_VAL
        add(tmpl, val=int(val), attr_label=format_attr(attr), attr_key=attr_key(attr))
    for tag, val in u.resists.items():
        if val:
            add(text.RESIST_VAL, val=val, tag_label=tag_label(tag))
    return [l for l in lines if l]

# ---------------------------------------------------------------------------
# Stat tagging (which stats an item modifies vs. scales with)
# ---------------------------------------------------------------------------
# Canonical set of player-facing stats we tag against. stat_names + a few
# extras that show up in tag/global bonuses (shot_cooldown, minion_range, ...).
STAT_KEYS = list(dict.fromkeys(
    list(stat_names) + ['minion_range', 'shot_cooldown', 'strikechance', 'cooldown']
))
STAT_KEYS_SET = set(STAT_KEYS)

def collect_bonus_stats(obj):
    """Stats this object *grants a bonus to* (modifies), from its bonus dicts."""
    out = set()
    for dname in ('global_bonuses', 'global_bonuses_pct'):
        d = getattr(obj, dname, None)
        if d:
            out.update(d.keys())
    for dname in ('tag_bonuses', 'tag_bonuses_pct', 'spell_bonuses', 'spell_bonuses_pct'):
        d = getattr(obj, dname, None)
        if d:
            for inner in d.values():
                out.update(inner.keys())
    return out

def buffs_from_tooltips(obj):
    out = []
    fn = getattr(obj, 'get_extra_examine_tooltips', None)
    if fn:
        try:
            for t in fn():
                if isinstance(t, BuffBase):
                    out.append(t)
        except Exception:
            pass
    return out

def equipment_stat_tags(e):
    """(modifies, uses) for a piece of equipment."""
    mods = collect_bonus_stats(e)
    for b in buffs_from_tooltips(e):
        mods |= collect_bonus_stats(b)
    uses = set(getattr(e, 'stats', []))
    return sorted(mods & STAT_KEYS_SET), sorted(uses & STAT_KEYS_SET)

def spell_stat_tags(s):
    """(modifies, uses) for a spell. 'uses' = stats it has/scales with;
    'modifies' = stats its upgrades or granted buffs add bonuses to."""
    uses = set(getattr(s, 'stats', []))
    mods = set()
    for up in getattr(s, 'spell_upgrades', []):
        mods |= collect_bonus_stats(up)
    for b in buffs_from_tooltips(s):
        mods |= collect_bonus_stats(b)
    return sorted(mods & STAT_KEYS_SET), sorted(uses & STAT_KEYS_SET)

# ---------------------------------------------------------------------------
# Units (summon stat sheets)
# ---------------------------------------------------------------------------
from Level import Unit, BUFF_TYPE_PASSIVE

UNITS = {}  # name -> stat sheet (deduped)

def _unit_ability(sp):
    a = {"name": sp.name}
    dt = getattr(sp, 'damage_type', None)
    if dt is not None and not isinstance(dt, list) and hasattr(dt, 'name'):
        a["damage_type"] = [dt.name]
    elif isinstance(dt, list):
        a["damage_type"] = [t.name for t in dt if hasattr(t, 'name')]
    for k in ['damage', 'range', 'radius', 'hp_cost']:
        if hasattr(sp, k):
            try:
                v = sp.get_stat(k)
            except Exception:
                v = getattr(sp, k, 0)
            if isinstance(v, (int, float)) and not isinstance(v, bool) and v:
                a[k] = v
    try:
        cd = sp.get_stat('cool_down') if hasattr(sp, 'cool_down') else 0
    except Exception:
        cd = getattr(sp, 'cool_down', 0)
    if cd:
        a["cool_down"] = cd
    try:
        if sp.get_stat('quick_cast'):
            a["quick_cast"] = True
    except Exception:
        pass
    try:
        desc = sp.description or sp.get_description()
        a["desc"] = rtext(desc or "", fmt=sp.fmt_dict())
    except Exception:
        a["desc"] = ""
    # melee attacks (range<=1, no damage line) still note "melee"
    if getattr(sp, 'melee', False):
        a["melee"] = True
    return a

def _unit_passives(u):
    # The game's examine panel shows ALL buffs for a unit not in a level (our
    # case) — only filtering to BUFF_TYPE_PASSIVE for live units. So include
    # every buff that yields tooltip text; this captures innate behaviours like
    # regeneration, spawn generators, and "chance to become" transformations.
    out = []
    seen = set()
    for b in u.buffs:
        txt = ""
        try:
            fmt = b.fmt_dict() if hasattr(b, 'fmt_dict') else {}
            txt = rtext(b.get_tooltip() or "", fmt=fmt)
        except Exception:
            txt = ""
        if not txt and b.name and b.name != "Unnamed buff":
            txt = b.name
        if txt and txt not in seen:
            seen.add(txt)
            out.append(txt)
    return out

def register_unit(u):
    """Extract + store a unit's stat sheet; return its name."""
    name = u.name
    if name in UNITS:
        return name
    # Apply tag-derived default resists (Undead -> Holy -100/Dark 100/Ice 50,
    # non-living -> Poison 100, Demon/Metallic/Glass, etc.). The game does this
    # lazily when a unit enters a level or is shown in the examine panel
    # (RiftWizard3.set_default_resistances), so a freshly-constructed unit's
    # `resists` is incomplete until we run it. Idempotent (guarded by
    # `resists_applied`) and self-contained (no level needed).
    try:
        u.set_default_resistances()
    except Exception:
        pass
    sheet = {
        "name": name,
        "hp": u.max_hp,
        "shields": getattr(u, 'shields', 0) or 0,
        "tags": [t.name for t in u.tags],
        "flying": bool(getattr(u, 'flying', False)),
        "stationary": bool(getattr(u, 'stationary', False)),
        "burrowing": bool(getattr(u, 'burrowing', False)),
        "radius": int(getattr(u, 'radius', 0) or 0),
        "is_boss": bool(getattr(u, 'is_boss', False)),
        "resists": {t.name: v for t, v in u.resists.items() if v},
        "abilities": [_unit_ability(sp) for sp in u.spells],
        "passives": _unit_passives(u),
        "refs": [],
        "btips": {},
        "icon": asset_filename(u.get_asset()),
    }
    cols, rows = sheet_grid(sheet["icon"], getattr(u, 'radius', 0))
    sheet["cols"] = cols     # idle-animation frame count (last row)
    sheet["rows"] = rows
    UNITS[name] = sheet
    return name

# ---------------------------------------------------------------------------
# Cross-references via static source analysis (AST)
# ---------------------------------------------------------------------------
# Instead of matching names in description prose (false positives), we read each
# class/factory's *source code* and find identifiers that are known game classes
# — e.g. Dread Lash's cast() contains `SealFate`, so it references Seal Fate.
import Monsters
import RareMonsters

FRAMEWORK_BASES = {'Spell', 'Equipment', 'Buff', 'Upgrade', 'Unit', 'Component', 'object'}
IDENT_MAP = {}     # python identifier -> (display_name, kind) ; value None == ambiguous
UNIT_FACTORY = {}  # unit display name -> its factory (for computing a unit's own refs)

def _register_factory(name, fac):
    if not name:
        return
    if name in UNIT_FACTORY and UNIT_FACTORY[name] is not fac:
        UNIT_FACTORY[name] = None    # ambiguous
    elif name not in UNIT_FACTORY:
        UNIT_FACTORY[name] = fac

def _register_ident(ident, name, kind):
    if not ident or not name:
        return
    cur = IDENT_MAP.get(ident, '__missing__')
    if cur == '__missing__':
        IDENT_MAP[ident] = (name, kind)
    elif cur is not None and cur != (name, kind):
        IDENT_MAP[ident] = None   # same identifier maps to >1 thing -> unusable

def build_ident_map(monster_factories):
    for cons in Spells.all_player_spell_constructors:
        try: _register_ident(cons.__name__, cons().name, 'spell')
        except Exception: pass
    # Forbidden spells too, so equipment that grants one (its source references
    # the spell class, e.g. BookOfChaos -> WordOfChaos) links to it.
    for s, _eq in forbidden_granted().values():
        try: _register_ident(type(s).__name__, s.name, 'spell')
        except Exception: pass
    for entry in Equipment.all_equipment:
        if isinstance(entry, type):
            try: _register_ident(entry.__name__, entry().name, 'equipment')
            except Exception: pass
    for fac in monster_factories:
        try: _register_ident(getattr(fac, '__name__', None), fac().name, 'unit')
        except Exception: pass
        _register_factory(getattr(_safe_call(fac), 'name', None), fac)
    # Also map every zero-arg unit factory in Monsters/RareMonsters (e.g.
    # BrainSapling, which only appears as a spawned minion) so code references
    # to them resolve. Refs to units without a card are pruned later.
    for mod in (Monsters, RareMonsters):
        for ident, obj in list(vars(mod).items()):
            if not callable(obj) or isinstance(obj, type):
                continue
            u = _safe_call(obj)
            if isinstance(u, Unit) and u.name:
                _register_ident(ident, u.name, 'unit')
                _register_factory(u.name, obj)

def _safe_call(fac):
    try:
        return fac()
    except Exception:
        return None

def _collect_idents(srcs):
    """Return (names, attrs): bare-name identifiers vs attribute accesses.
    The split matters for buffs: a buff class is referenced by bare name
    (`Poison`, `NecrosisBuff`), whereas `Tags.Poison` is an attribute — same
    word, different meaning (the damage type). Buff resolution uses names only."""
    names, attrs = set(), set()
    for src in srcs:
        if not src:
            continue
        try:
            tree = ast.parse(textwrap.dedent(src))
        except (SyntaxError, ValueError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Name):
                names.add(node.id)
            elif isinstance(node, ast.Attribute):
                attrs.add(node.attr)
    return names, attrs

_SRC_CACHE = {}
def _getsource(o):
    key = id(o)
    if key not in _SRC_CACHE:
        try:
            _SRC_CACHE[key] = inspect.getsource(o)
        except Exception:
            _SRC_CACHE[key] = None
    return _SRC_CACHE[key]

# --- Buffs (named status effects with no card of their own) -----------------
# A unit ability like "gain a stack of Brewed Concoctions" names a Buff that's
# never explained on-screen. We surface each such buff's description as a
# hover-only glossary tooltip. Buff class identifiers live in their OWN map
# (not IDENT_MAP) so that a buff class sharing a name with a real spell/unit
# can never neutralize that identifier (see _register_ident's collision rule).
# A buff ref is only ever emitted when an entity's source *code* references the
# buff class — same AST rigor as the cross-references above, so no prose matches.
BUFF_IDENT = {}    # class identifier -> buff display name  (None == ambiguous)
BUFF_CLASS = {}    # class identifier -> Buff subclass       (None == ambiguous)

def _literal_args(call_args):
    """Python values of an ast.Call's positional args, or None if any isn't a
    literal (a variable / stat lookup we can't evaluate statically)."""
    vals = []
    for a in call_args:
        if isinstance(a, ast.Constant):
            vals.append(a.value)
        elif (isinstance(a, ast.UnaryOp) and isinstance(a.op, ast.USub)
              and isinstance(a.operand, ast.Constant)):
            vals.append(-a.operand.value)
        else:
            return None
    return tuple(vals)

def _buff_call_args(srcs):
    """ident -> the literal positional args the source constructs it with, so a
    buff's tooltip reflects the value actually applied (RegenBuff's heal ranges
    1..100 across the game). First all-literal call site wins; ties are rare."""
    out = {}
    for src in srcs:
        if not src:
            continue
        try:
            tree = ast.parse(textwrap.dedent(src))
        except (SyntaxError, ValueError):
            continue
        for node in ast.walk(tree):
            if (isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                    and node.func.id in BUFF_CLASS and node.func.id not in out):
                lits = _literal_args(node.args)
                if lits is not None:
                    out[node.func.id] = lits
    return out

def _resolve_buff(ident, args):
    """Build a buff's {desc, color} from the class the source references and the
    args it applies (falling back to filler args if the call wasn't literal)."""
    cls = BUFF_CLASS.get(ident)
    if cls is None:
        return None
    b = None
    if args is not None:
        try:
            b = cls(*args)
        except Exception:
            b = None
    if b is None:
        b = _construct_buff(cls)
    if b is None:
        return None
    desc = _buff_text(b)
    if not desc:
        return None
    col = getattr(b, 'color', None)
    return {"desc": desc, "color": to_tup(col) if isinstance(col, Color) else None}

def _construct_buff(cls):
    """Instantiate a Buff for its name/description. Many buffs need constructor
    args (e.g. RegenBuff(heal), DamageAuraBuff(damage, ...)); a zero-arg attempt
    would skip them entirely — and they'd be silently unlinkable (the Witch
    Doctor's Regeneration). Fall back to filler positional args; the name and
    description template are what we read, and those don't depend on the values."""
    for args in ((), (1,), (1, 1), (1, 1, 1), (1, 1, 1, 1)):
        try:
            return cls(*args)
        except Exception:
            continue
    return None

def _buff_text(b):
    for meth in ('get_description', 'get_tooltip'):
        f = getattr(b, meth, None)
        if not f:
            continue
        try:
            fmt = b.fmt_dict() if hasattr(b, 'fmt_dict') else {}
            txt = f()
            if txt:
                rendered = rtext(txt, fmt=fmt)
                # A standalone "None" means a fmt value was empty because we
                # filler-constructed the buff (e.g. ChannelBuff's {spell} with no
                # real spell). That description is an artifact, not real text.
                if re.search(r'(?<![A-Za-z])None(?![A-Za-z])', rendered):
                    return ""
                return rendered
        except Exception:
            continue
    return ""

def _all_subclasses(cls):
    seen, stack = set(), [cls]
    while stack:
        for sub in stack.pop().__subclasses__():
            if sub not in seen:
                seen.add(sub)
                stack.append(sub)
    return seen

def build_buff_map():
    # Import the content modules that define buffs, then walk the Buff class tree
    # directly (not any module's __dict__). This is order-independent and complete,
    # so the shipped buff set is stable across rebuilds regardless of import quirks.
    import CommonContent, Level  # noqa: F401  (ensure their buffs are loaded)
    from Level import Buff
    # A buff whose name collides with a damage-type Tag (e.g. "Poison") is still
    # registered — disambiguation happens at reference time: `refs_for` links it
    # only from a bare-name class reference (not `Tags.Poison`), and the frontend
    # never linkifies a buff name inside a [markup] token (the damage type).
    # Map class identifier -> (display name, class). The description itself is NOT
    # finalized here — it's resolved per reference site from the actual args (see
    # _resolve_buff), because e.g. RegenBuff's heal amount differs everywhere.
    for cls in sorted(_all_subclasses(Buff), key=lambda c: c.__name__):
        ident = cls.__name__
        b = _construct_buff(cls)
        if b is None:
            continue
        name = getattr(b, 'name', None)
        if not name or name == 'Unnamed buff':
            continue
        if not _buff_text(b):
            continue    # no describable text even with filler args -> not a glossary buff
        if ident in BUFF_IDENT and BUFF_IDENT[ident] != name:
            BUFF_IDENT[ident] = BUFF_CLASS[ident] = None   # same ident -> >1 buff: unusable
        elif ident not in BUFF_IDENT:
            BUFF_IDENT[ident] = name
            BUFF_CLASS[ident] = cls

def refs_for(instance, entry, self_name):
    """Return (refs, btips): refs = [[display_name, kind], …] this entity
    references in its code; btips = {buff_name: {desc, color}} resolved from the
    actual class + args the source applies (so tooltips are exact, per site)."""
    srcs = [_getsource(entry)]                   # the registry entry (class / factory / lambda)
    cls = type(instance)
    if isinstance(cls, type):
        for base in cls.__mro__:                 # base-class method bodies (generic logic)
            if base is object or base.__name__ in FRAMEWORK_BASES:
                continue
            srcs.append(_getsource(base))
    names, attrs = _collect_idents(srcs)
    call_args = _buff_call_args(srcs)
    out, seen, btips = [], set(), {}
    for ident in names | attrs:
        m = IDENT_MAP.get(ident)
        if m:
            name, kind = m
        elif ident in names and BUFF_IDENT.get(ident):
            # Buffs fall back to the glossary, but only from a bare-name class
            # reference — never an attribute. So `Tags.Poison` (the damage type)
            # can't masquerade as the Poison status buff, while a literal `Poison`
            # reference (e.g. the Witch Doctor's hex) still links.
            name, kind = BUFF_IDENT[ident], 'buff'
        else:
            continue
        if name == self_name or name in seen:
            continue
        if kind == 'buff':
            info = _resolve_buff(ident, call_args.get(ident))
            if not info:                         # can't describe it -> don't link it
                continue
            btips[name] = info
        seen.add(name)
        out.append([name, kind])
    out.sort()
    return out, btips

# ---------------------------------------------------------------------------
# Full monster roster (bestiary): base spawns + evolutions + rare rosters
# ---------------------------------------------------------------------------

MONSTER_NAMES = set()   # names that belong to the bestiary
MONSTER_DEPTH = {}      # name -> earliest spawn depth (base monsters only)

def collect_monster_factories():
    factories = {}        # factory -> earliest depth (or None)
    for entry in Monsters.spawn_options:
        base, depth = entry[0], entry[1]
        factories.setdefault(base, depth)
        if factories[base] is None or (depth and depth < factories[base]):
            factories[base] = depth
        if len(entry) > 2 and entry[2]:
            factories.setdefault(entry[2], None)
    for list_name in ['MONSTER_PACKS', 'IDOLS', 'SUPER_SPAWNERS', 'SPECIAL_MONSTERS', 'WIZARDS', 'KAIJU']:
        L = getattr(RareMonsters, list_name, None) or []
        for entry in L:
            factories.setdefault(entry[0], None)
    return factories

def extract_monsters(factories):
    for fac, depth in factories.items():
        try:
            u = fac()
        except Exception as e:
            print("skip monster", getattr(fac, '__name__', fac), e)
            continue
        if not isinstance(u, Unit):
            continue
        register_unit(u)
        # factory is authoritative for monsters
        UNITS[u.name]["refs"], UNITS[u.name]["btips"] = refs_for(u, fac, u.name)
        MONSTER_NAMES.add(u.name)
        if depth is not None:
            cur = MONSTER_DEPTH.get(u.name)
            MONSTER_DEPTH[u.name] = depth if cur is None else min(cur, depth)

# ---------------------------------------------------------------------------
# Companions: permanent allies bought at the Tavern (Equipment.all_companions).
# The companion is an Equipment whose examine tooltip is the (buffed) unit it
# summons, but it's neither craftable (not in all_equipment) nor part of the
# bestiary — so its unit is otherwise absent. Extract those units and flag them
# as their own Monsters-tab category ("Companion"). The buffed stats match what
# you see in-game (make_minion applies the companion's minion_* bonuses).
# ---------------------------------------------------------------------------
COMPANION_NAMES = set()

def extract_companions():
    for cons in getattr(Equipment, 'all_companions', []):
        e = _safe_call(cons)
        if e is None:
            continue
        fac = getattr(e, 'unit_fn', None)          # zero-arg factory for the base unit
        if fac:                                    # enable AST cross-refs + name links
            u = _safe_call(fac)
            if isinstance(u, Unit) and u.name:
                _register_ident(getattr(fac, '__name__', None), u.name, 'unit')
                _register_factory(u.name, fac)
        # summons_of registers the companion unit AND any units it in turn
        # summons (e.g. the Engineer's Auto Cannon, the Ranger's Giant Bear).
        # Only the companion itself is a "Companion"; its summons stay plain
        # summonables. Companion.name == the summoned unit's name (unit_ex.name).
        registered = set(summons_of(e))
        if e.name in registered:
            COMPANION_NAMES.add(e.name)

def summons_of(obj):
    """Return list of distinct unit names this spell/equipment/component can summon."""
    names = []
    seen = set()

    def add(u):
        if isinstance(u, Unit) and u.name not in seen:
            seen.add(u.name)
            register_unit(u)
            names.append(u.name)

    fn = getattr(obj, 'get_extra_examine_tooltips', None)
    if fn:
        try:
            for t in fn():
                add(t)
        except Exception:
            pass
    gu = getattr(obj, 'get_unit', None)
    if gu:
        try:
            add(gu())
        except Exception:
            pass
    return names

# ---------------------------------------------------------------------------
# Spells
# ---------------------------------------------------------------------------
# Stat lines shown on a spell card. Mirrors the game's spell examine panel:
# the dedicated range/charges/hp_cost lines it draws first, then every TT_ATTRS
# attribute (the "Attributes:" section). Derived from TT_ATTRS so channel/minion
# stats (e.g. max_channel) can't silently drop off again as the game evolves.
SPELL_STAT_KEYS = ['range', 'max_charges', 'hp_cost'] + list(TT_ATTRS)

def _spell_entry(s, cons, forbidden=False, granted_by=None):
    fmt = s.fmt_dict()
    stats = {}
    for k in SPELL_STAT_KEYS:
        if hasattr(s, k):
            v = s.get_stat(k)
            if isinstance(v, (int, float)) and not isinstance(v, bool) and v:
                stats[k] = v
    dtypes = []
    dt = getattr(s, 'damage_type', None)
    if dt:
        if isinstance(dt, list):
            dtypes = [t.name for t in dt]
        else:
            dtypes = [dt.name]
    upgrades = []
    for u in s.spell_upgrades:
        # Game order: auto-generated stat lines first, then prose (some
        # upgrades, e.g. Relentless Cascade, are pure stat with no prose).
        prose = rtext(u.get_description() or "", fmt=u.fmt_dict())
        parts = upgrade_bonus_lines(u) + ([prose] if prose else [])
        upgrades.append({
            "name": u.name,
            "level": getattr(u, 'level', 0),
            "desc": "\n".join(parts),
        })
    mod_stats, use_stats = spell_stat_tags(s)
    refs, btips = refs_for(s, cons, s.name)
    entry = {
        "name": s.name,
        "level": s.level,
        "tags": [t.name for t in s.tags],
        "damage_type": dtypes,
        "stats": stats,
        "requires_los": bool(getattr(s, 'requires_los', True)),
        "melee": bool(getattr(s, 'melee', False)),
        "quick_cast": bool(getattr(s, 'quick_cast', False)),
        "desc": rtext(s.get_description() or "", fmt=fmt),
        "upgrades": upgrades,
        "summons": summons_of(s),
        "refs": refs,
        "btips": btips,
        "mod_stats": mod_stats,
        "use_stats": use_stats,
        "icon": asset_filename(s.get_asset()),
    }
    if forbidden:
        # Forbidden spells aren't bought with SP — they come with a SpellBook.
        # The frontend shows "Forbidden" instead of an SP cost and links the
        # granting equipment. They're excluded from Guide SP ids (see main()).
        entry["forbidden"] = True
        if granted_by:
            entry["granted_by"] = granted_by
            entry["refs"] = sorted(set(map(tuple, entry["refs"])) | {(granted_by, "equipment")})
    return entry

_FORBIDDEN = None
def forbidden_granted():
    """Map forbidden-spell name -> (spell instance, granting equipment name).
    Forbidden spells can't be learned with SP — they're granted only by SpellBook
    equipment (e.g. Word of Chaos from Book of Chaos). Detected as equipment-
    granted spells whose name isn't in the normal player roster, so staves that
    re-grant a *normal* spell don't produce duplicates. Cached (instantiates
    every equipment once); also feeds build_ident_map so the book's description
    can link the spell."""
    global _FORBIDDEN
    if _FORBIDDEN is None:
        player_names = {cons().name for cons in Spells.all_player_spell_constructors}
        found = {}
        for cons in Equipment.all_equipment:
            try:
                e = cons()
            except Exception:
                continue
            granted = []
            sp = getattr(e, 'spell', None)
            if isinstance(sp, Spell):
                granted.append(sp)
            try:
                for t in (e.get_extra_examine_tooltips() or []):
                    if isinstance(t, Spell):
                        granted.append(t)
            except Exception:
                pass
            for s in granted:
                if s.name not in player_names and s.name not in found:
                    found[s.name] = (s, e.name)
        _FORBIDDEN = found
    return _FORBIDDEN

def extract_spells():
    out = [_spell_entry(cons(), cons) for cons in Spells.all_player_spell_constructors]
    out += [_spell_entry(s, type(s), forbidden=True, granted_by=eq)
            for s, eq in forbidden_granted().values()]
    # Forbidden spells sort to the end (they're a distinct, SP-less category).
    out.sort(key=lambda d: (bool(d.get("forbidden")), d["level"], d["name"]))
    return out

# ---------------------------------------------------------------------------
# Equipment
# ---------------------------------------------------------------------------
def extract_equipment():
    out = []
    for cons in Equipment.all_equipment:
        try:
            e = cons()
        except Exception as ex:
            print("skip equipment", cons, ex)
            continue
        recipe = []
        for tag, amt in getattr(e, 'recipe', []):
            recipe.append([tag.name, int(amt)])
        desc = rtext(e.get_description() or "", fmt=e.fmt_dict())
        bonus_lines = render_bonus_lines(e)
        mod_stats, use_stats = equipment_stat_tags(e)
        # A SpellBook/staff delegates its examine tooltips to the spell it grants,
        # so summons_of(e) picks up the SPELL's summons (e.g. Word of Chaos's
        # Chaos Spirit) and misattributes them to the book. Those belong to the
        # spell's card; subtract them so the equipment lists only what it itself
        # summons directly.
        gs = getattr(e, 'spell', None)
        granted_units = set(summons_of(gs)) if isinstance(gs, Spell) else set()
        summons = [n for n in summons_of(e) if n not in granted_units]
        refs, btips = refs_for(e, cons, e.name)
        out.append({
            "name": e.name,
            "slot": SLOT_NAMES.get(getattr(e, 'slot', 0), "Trinket"),
            "tags": [t.name for t in e.tags],
            "recipe": recipe,
            "recipe_cost": sum(a for _, a in recipe),
            "desc": desc,
            "bonuses": bonus_lines,
            "summons": summons,
            "refs": refs,
            "btips": btips,
            "mod_stats": mod_stats,
            "use_stats": use_stats,
            "icon": asset_filename(e.get_asset()),
        })
    out.sort(key=lambda d: (d["recipe_cost"], d["name"]))
    return out

# ---------------------------------------------------------------------------
# Components
# ---------------------------------------------------------------------------
def extract_components():
    out = []
    tier_of = {}
    for c in Components.t1_components: tier_of[c] = 1
    for c in Components.t2_components: tier_of[c] = 2
    for c in Components.t3_components: tier_of[c] = 3
    seen = []
    pools = [("normal", Components.all_components), ("rare", Components.rare_components)]
    for pool_name, pool in pools:
        for cons in pool:
            c = cons()
            tier = tier_of.get(cons, len(c.tags))
            has_craft = type(c).on_craft is not ComponentBase.on_craft
            has_pickup = type(c).on_pickup is not ComponentBase.on_pickup
            refs, btips = refs_for(c, cons, c.name)
            out.append({
                "name": c.name,
                "tags": [t.name for t in c.tags],
                "tier": tier,
                "rare": bool(getattr(c, 'is_rare', False)) or pool_name == "rare",
                "pool": pool_name,
                "on_craft": has_craft,
                "on_pickup": has_pickup,
                "desc": rtext(getattr(c, 'description', "") or "", fmt={}),
                "summons": summons_of(c),
                "refs": refs,
                "btips": btips,
                "icon": asset_filename(c.get_asset()),
            })
    out.sort(key=lambda d: (d["tier"], d["name"]))
    return out

# ---------------------------------------------------------------------------
# Tags metadata
# ---------------------------------------------------------------------------
def extract_tags():
    # component_tags are the craftable/recipe tags
    comp_tags = [t.name for t in Components.component_tags]
    tags = {}
    for tag in Tags:
        tags[tag.name] = {"color": to_tup(tag.color)}
    # Single-letter essence codes shown in the crafting UI. The game derives them
    # from the tag-filter hotkeys (RiftWizard3.KEY_BIND_DEFS); mirrored here (UI
    # module isn't imported — same reason tooltip_colors are mirrored). Distinct
    # letters resolve first-letter clashes (Eye=Y, Dragon=R, Chaos=K, Slime=Z,
    # Ritual=U, Any=∗). Keep in sync with TAG_ABBR in app.js.
    tag_abbr = {
        "Any": "∗", "Fire": "F", "Ice": "I", "Lightning": "L", "Nature": "N",
        "Arcane": "A", "Dark": "D", "Holy": "H", "Metallic": "M", "Blood": "B",
        "Sorcery": "S", "Enchantment": "E", "Conjuration": "C", "Eye": "Y",
        "Dragon": "R", "Orb": "O", "Chaos": "K", "Slime": "Z", "Word": "W",
        "Translocation": "T", "Ritual": "U",
    }
    for name, ab in tag_abbr.items():
        if name in tags:
            tags[name]["abbr"] = ab
    return {"all": tags, "component_tags": comp_tags}

def main():
    monster_factories = collect_monster_factories()
    build_ident_map(monster_factories.keys())   # must precede any refs_for() call
    build_buff_map()                            # buff glossary; also feeds refs_for()
    spells = extract_spells()
    equipment = extract_equipment()
    components = extract_components()            # these populate UNITS via summons_of()
    extract_monsters(monster_factories)         # full bestiary into UNITS
    extract_companions()                         # Tavern companions into UNITS
    # annotate units with monster-roster metadata + factory-derived refs
    for name, sheet in UNITS.items():
        sheet["is_monster"] = name in MONSTER_NAMES
        sheet["is_companion"] = name in COMPANION_NAMES
        if name in MONSTER_DEPTH:
            sheet["depth"] = MONSTER_DEPTH[name]
        fac = UNIT_FACTORY.get(name)
        if fac:
            inst = _safe_call(fac)
            if inst is not None:
                refs, btips = refs_for(inst, fac, name)
                # A unit's own permanent buffs are already shown in full under
                # Passives; don't also linkify their names on the card. Without
                # this, the Vampire Hunter's "Silvered Weapons" passive got a
                # redundant self-link on the word "Silvered" (SilveredBuff.name).
                # Buffs a unit merely grants or applies conditionally aren't in
                # u.buffs (e.g. the Alchemist's Brewed Concoctions), so they stay.
                own_buffs = {getattr(b, 'name', None) for b in getattr(inst, 'buffs', [])}
                sheet["refs"] = [r for r in refs if not (r[1] == 'buff' and r[0] in own_buffs)]
                sheet["btips"] = btips
    # Prune cross-refs whose target has no card (e.g. units that are never
    # surfaced), so every link resolves to a real entry.
    valid = {'spell': {s['name'] for s in spells},
             'equipment': {e['name'] for e in equipment},
             'unit': set(UNITS.keys())}
    def finalize(entity_name, refs, btips):
        kept = []
        for r in refs:
            if r[1] == 'buff':
                # buff refs are pre-validated (only added when describable); drop a
                # buff whose name is a whole word of the entity's OWN name, whose
                # name recurs throughout its own text (e.g. "Poison Sting gains …")
                # and would self-link the shared word "Poison" onto the Poison buff.
                if r[0] in btips and not re.search(
                        r'(?<![A-Za-z])' + re.escape(r[0]) + r'(?![A-Za-z])', entity_name):
                    kept.append(r)
            elif r[0] in valid.get(r[1], ()):
                kept.append(r)
        keep_buffs = {r[0] for r in kept if r[1] == 'buff'}
        return kept, {n: v for n, v in btips.items() if n in keep_buffs}
    for it in spells + equipment + components:
        it['refs'], it['btips'] = finalize(it['name'], it['refs'], it.get('btips', {}))
    for name, sheet in UNITS.items():
        sheet['refs'], sheet['btips'] = finalize(name, sheet['refs'], sheet.get('btips', {}))
    # Stable integer ids for shareable build URLs (append-only; see ids.py).
    # Mutates ids.json on disk — it MUST be committed alongside data.json.
    idmap = ids_mod.load_ids()
    # Forbidden spells are equipment-granted (no SP cost), so they get no spell
    # id and don't enter the Guide SP track (assign_sp skips them internally).
    learnable = [s for s in spells if not s.get("forbidden")]
    ids_mod.assign(idmap, "equipment", [e["name"] for e in equipment])
    ids_mod.assign(idmap, "spell", [s["name"] for s in learnable])
    ids_mod.assign_sp(idmap, spells)   # combined spell+upgrade ids (Guide SP track)
    ids_mod.save_ids(idmap)
    for e in equipment: e["id"] = idmap["equipment"][e["name"]]
    for s in learnable: s["id"] = idmap["spell"][s["name"]]
    data = {
        "spells": spells,
        "equipment": equipment,
        "components": components,
        "units": UNITS,
        "tags": extract_tags(),
        "colors": tooltip_colors,
        "slots": list(SLOT_NAMES.values()),
        "stat_meta": {k: format_attr(k) for k in STAT_KEYS},
        "generated": __import__("datetime").date.today().isoformat(),
    }
    out_path = os.path.join(OUT_DIR, "data.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
    monsters = sum(1 for s in UNITS.values() if s.get("is_monster"))
    companions = sum(1 for s in UNITS.values() if s.get("is_companion"))
    distinct_buffs = set()
    for it in spells + equipment + components + list(UNITS.values()):
        distinct_buffs.update(it.get("btips", {}))
    print("Wrote", out_path)
    print("spells:", len(data["spells"]), "equipment:", len(data["equipment"]),
          "components:", len(data["components"]), "units:", len(data["units"]),
          "(monsters:", monsters, "companions:", companions, ")",
          "distinct buffs linked:", len(distinct_buffs))

if __name__ == "__main__":
    main()
