"""
Extract Rift Wizard 3 spell / equipment / component data into a JSON file
for the static browser resource. Reads ONLY from the game install dir;
writes only into this project's site/ folder.
"""
import os, sys, json, ast, inspect, textwrap

os.environ['SDL_VIDEODRIVER'] = 'dummy'
os.environ['SDL_AUDIODRIVER'] = 'dummy'

GAME = r"E:\SteamLibrary\steamapps\common\Rift Wizard 3 Demo"
HERE = os.path.dirname(os.path.abspath(__file__))

import ids as ids_mod  # stable append-only id assignment (HERE-relative; safe before chdir)
OUT_DIR = os.path.join(HERE, "site")
os.makedirs(OUT_DIR, exist_ok=True)

sys.path.insert(0, GAME)
os.chdir(GAME)  # so rl_data/loc text json loads

# Import order matters (circular imports): Equipment pulls Level/CommonContent/Monsters/Spells/Components.
import Equipment
import Spells
import Components
import text
from Level import (resolve_text, Tags, attr_colors, format_attr, tag_key, attr_key,
                   tag_label, Equipment as EquipmentBase, Component as ComponentBase,
                   Buff as BuffBase, stat_names)

# ---------------------------------------------------------------------------
# Color map: replicate RiftWizard3.tooltip_colors without importing the UI.
# ---------------------------------------------------------------------------
def to_tup(c):
    return [c.r, c.g, c.b]

COLOR_DAMAGE = type(Tags.Fire.color)(215, 0, 0)
Color = type(Tags.Fire.color)

tooltip_colors = {}
for tag in Tags:
    tooltip_colors[tag.name.lower()] = to_tup(tag.color)
for k, v in attr_colors.items():
    tooltip_colors[k] = to_tup(v)
tooltip_colors['default'] = [255, 255, 255]

# manual additions mirrored from RiftWizard3.py
_manual = {
    'petrify': Tags.Construct, 'petrified': Tags.Construct, 'petrifies': Tags.Construct,
    'frozen': Tags.Ice, 'freezes': Tags.Ice, 'freeze': Tags.Ice,
    'stunned': Tags.Physical, 'stun': Tags.Physical, 'stuns': Tags.Physical,
    'poisoned': Tags.Poison, 'poisons': Tags.Poison,
    'glassify': Tags.Glass, 'glassified': Tags.Glass, 'glassed': Tags.Glass,
    'sleep': Tags.Arcane, 'sleeps': Tags.Arcane,
    'silence': Tags.Arcane, 'silenced': Tags.Arcane, 'silences': Tags.Arcane,
    'necrosis': Tags.Dark, 'fear': Tags.Dark, 'fears': Tags.Dark, 'feared': Tags.Dark,
    'blind': Tags.Eye, 'blinds': Tags.Eye, 'blinded': Tags.Eye,
    'bleed': Tags.Blood, 'bleeds': Tags.Blood, 'bleeding': Tags.Blood, 'hemorrhage': Tags.Blood,
    'requires_los': Tags.Translocation, 'ally': Tags.Conjuration, 'hp_cost': Tags.Blood,
}
for k, tg in _manual.items():
    tooltip_colors[k] = to_tup(tg.color)
tooltip_colors['berserk'] = to_tup(COLOR_DAMAGE)
tooltip_colors['berserked'] = to_tup(COLOR_DAMAGE)
tooltip_colors['berserks'] = to_tup(COLOR_DAMAGE)
tooltip_colors['enemy'] = to_tup(COLOR_DAMAGE)
tooltip_colors['wizard'] = [2, 136, 209]
tooltip_colors['quick_cast'] = [255, 255, 255]
tooltip_colors['max_channel'] = [153, 51, 102]

# ---------------------------------------------------------------------------
# Slots
# ---------------------------------------------------------------------------
SLOT_NAMES = {0: "Trinket", 1: "Head", 2: "Body", 3: "Feet", 4: "Weapon"}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def rtext(value, fmt=None):
    try:
        return resolve_text(value, fmt=fmt)
    except Exception as e:
        return ""

def asset_filename(get_asset_result):
    # last element + .png, lowercased for the web
    return (get_asset_result[-1] + ".png").lower()

# --- sprite sheet dimensions (for pure-CSS idle animation) ------------------
# Read PNG width/height straight from the IHDR header — no image library needed
# (avoids an SDL/pygame DLL conflict when cwd is the game dir).
import struct
_CHAR_DIR = os.path.join(GAME, "rl_data", "char")
_char_index = None
def _char_path(icon):
    global _char_index
    if _char_index is None:
        _char_index = {}
        for fn in os.listdir(_CHAR_DIR):
            if fn.lower().endswith(".png"):
                _char_index[fn.lower()] = os.path.join(_CHAR_DIR, fn)
    return _char_index.get(icon.lower())

def _png_size(path):
    with open(path, "rb") as f:
        head = f.read(24)
    if len(head) < 24 or head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return struct.unpack(">II", head[16:24])   # width, height

def sheet_grid(icon, radius):
    """(columns, rows) of a char spritesheet; idle = last row, cols = idle frames."""
    p = _char_path(icon)
    if not p:
        return (1, 1)
    try:
        w, h = _png_size(p)
    except Exception:
        return (1, 1)
    base = 60 if w % 60 == 0 else 16
    fs = base * (1 + 2 * (radius or 0))
    if fs <= 0 or w % fs or h % fs:
        return (1, 1)
    return (w // fs, h // fs)

def render_bonus_lines(o):
    """Replicate the autogenerated bonus tooltip lines for an equipment/buff."""
    lines = []
    for tag, bonuses in o.tag_bonuses_pct.items():
        for attr, val in bonuses.items():
            lines.append(rtext((text.TAG_PCT_BONUS, {
                "tag_label": tag_label(tag), "tag_key": tag_key(tag),
                "val": int(val), "attr_label": format_attr(attr), "attr_key": attr_key(attr)})))
    for tag, bonuses in o.tag_bonuses.items():
        for attr, val in bonuses.items():
            lines.append(rtext((text.TAG_VAL_BONUS, {
                "tag_label": tag_label(tag), "tag_key": tag_key(tag),
                "val": int(val), "attr_label": format_attr(attr), "attr_key": attr_key(attr)})))
    for attr, val in o.global_bonuses_pct.items():
        tmpl = text.ALL_GAIN_PCT if val >= 0 else text.ALL_LOSE_PCT
        lines.append(rtext((tmpl, {"val": int(val), "attr_label": format_attr(attr), "attr_key": attr_key(attr)})))
    for attr, val in o.global_bonuses.items():
        tmpl = text.ALL_GAIN_VAL if val >= 0 else text.ALL_LOSE_VAL
        lines.append(rtext((tmpl, {"val": int(val), "attr_label": format_attr(attr), "attr_key": attr_key(attr)})))
    for tag, val in o.resists.items():
        if val:
            lines.append(rtext((text.RESIST_VAL, {"val": val, "tag_label": tag_label(tag)})))
    return [l for l in lines if l]

# Mirror of RiftWizard3.tt_attrs, in the game's own order (the UI module isn't
# importable in the build env — no steamworks — same reason tooltip_colors are
# mirrored, §2). This is the game's canonical attribute list: it's what the
# spell examine "Attributes:" section iterates, and the only new_attributes an
# upgrade tooltip surfaces as a text line. Keep it a tuple (order matters for
# spell stat-line display) — `in` membership checks still work.
TT_ATTRS = (
    'num_targets', 'damage', 'duration', 'radius', 'shields', 'shot_cooldown',
    'strikechance', 'cooldown', 'max_channel', 'num_summons', 'minion_health',
    'minion_damage', 'minion_duration', 'minion_range',
)

def upgrade_bonus_lines(u):
    """Replicate the game's auto-generated upgrade tooltip lines — the stat
    deltas the examine panel draws above an upgrade's prose. Pure-stat upgrades
    (e.g. Relentless Cascade: +2 range/+3 charges) have NO prose at all, so
    without these they render blank. Order mirrors RiftWizard3.draw_examine's
    upgrade branch; the colored-vs-plain choice keys off tooltip_colors exactly
    as the game does (attr names are never tag/status keys, so spell/global stat
    lines come out plain — matching the game)."""
    lines = []
    def add(tmpl, **kw): lines.append(rtext((tmpl, kw)))
    for tag, bonuses in u.tag_bonuses_pct.items():
        for attr, val in bonuses.items():
            add(text.TAG_PCT_BONUS, tag_label=tag_label(tag), tag_key=tag_key(tag),
                val=int(val), attr_label=format_attr(attr), attr_key=attr_key(attr))
    for tag, bonuses in u.tag_bonuses.items():
        for attr, val in bonuses.items():
            add(text.TAG_VAL_BONUS, tag_label=tag_label(tag), tag_key=tag_key(tag),
                val=int(val), attr_label=format_attr(attr), attr_key=attr_key(attr))
    # Per-spell bonuses: the game only shows attrs the target spell actually has.
    for spell, bonuses in u.spell_bonuses_pct.items():
        sp = spell()
        for attr, val in bonuses.items():
            if attr not in sp.stats: continue
            tmpl = text.GAIN_PCT_COLORED if attr in tooltip_colors else text.GAIN_PCT_PLAIN
            add(tmpl, name=sp.name, val=val, attr_label=format_attr(attr), attr_key=attr_key(attr))
    for spell, bonuses in u.spell_bonuses.items():
        sp = spell()
        for attr, val in bonuses.items():
            if attr not in sp.stats: continue
            tmpl = text.GAIN_VAL_COLORED if attr in tooltip_colors else text.GAIN_VAL_PLAIN
            add(tmpl, name=sp.name, val=val, attr_label=format_attr(attr), attr_key=attr_key(attr))
    prereq = getattr(u, 'prereq', None)
    if prereq is not None:
        for attr, val in getattr(u, 'new_attributes', {}).items():
            if attr in TT_ATTRS or attr == 'hp_cost':  # game always colors these
                add(text.GAIN_VAL_COLORED, name=prereq.name, val=val,
                    attr_label=format_attr(attr), attr_key=attr_key(attr))
    for attr, val in u.global_bonuses_pct.items():
        tmpl = text.ALL_GAIN_PCT if val >= 0 else text.ALL_LOSE_PCT
        add(tmpl, val=int(val), attr_label=format_attr(attr), attr_key=attr_key(attr))
    for attr, val in u.global_bonuses.items():
        tmpl = text.ALL_GAIN_VAL if val >= 0 else text.ALL_LOSE_VAL
        add(tmpl, val=int(val), attr_label=format_attr(attr), attr_key=attr_key(attr))
    for tag, val in u.resists.items():
        if val:
            add(text.RESIST_VAL, val=val, tag_label=tag_label(tag))
    return [l for l in lines if l]

# ---------------------------------------------------------------------------
# Stat tagging (which stats an item modifies vs. scales with)
# ---------------------------------------------------------------------------
# Canonical set of player-facing stats we tag against. stat_names + a few
# extras that show up in tag/global bonuses (shot_cooldown, minion_range, ...).
STAT_KEYS = list(dict.fromkeys(
    list(stat_names) + ['minion_range', 'shot_cooldown', 'strikechance', 'cooldown']
))
STAT_KEYS_SET = set(STAT_KEYS)

def collect_bonus_stats(obj):
    """Stats this object *grants a bonus to* (modifies), from its bonus dicts."""
    out = set()
    for dname in ('global_bonuses', 'global_bonuses_pct'):
        d = getattr(obj, dname, None)
        if d:
            out.update(d.keys())
    for dname in ('tag_bonuses', 'tag_bonuses_pct', 'spell_bonuses', 'spell_bonuses_pct'):
        d = getattr(obj, dname, None)
        if d:
            for inner in d.values():
                out.update(inner.keys())
    return out

def buffs_from_tooltips(obj):
    out = []
    fn = getattr(obj, 'get_extra_examine_tooltips', None)
    if fn:
        try:
            for t in fn():
                if isinstance(t, BuffBase):
                    out.append(t)
        except Exception:
            pass
    return out

def equipment_stat_tags(e):
    """(modifies, uses) for a piece of equipment."""
    mods = collect_bonus_stats(e)
    for b in buffs_from_tooltips(e):
        mods |= collect_bonus_stats(b)
    uses = set(getattr(e, 'stats', []))
    return sorted(mods & STAT_KEYS_SET), sorted(uses & STAT_KEYS_SET)

def spell_stat_tags(s):
    """(modifies, uses) for a spell. 'uses' = stats it has/scales with;
    'modifies' = stats its upgrades or granted buffs add bonuses to."""
    uses = set(getattr(s, 'stats', []))
    mods = set()
    for up in getattr(s, 'spell_upgrades', []):
        mods |= collect_bonus_stats(up)
    for b in buffs_from_tooltips(s):
        mods |= collect_bonus_stats(b)
    return sorted(mods & STAT_KEYS_SET), sorted(uses & STAT_KEYS_SET)

# ---------------------------------------------------------------------------
# Units (summon stat sheets)
# ---------------------------------------------------------------------------
from Level import Unit, BUFF_TYPE_PASSIVE

UNITS = {}  # name -> stat sheet (deduped)

def _unit_ability(sp):
    a = {"name": sp.name}
    dt = getattr(sp, 'damage_type', None)
    if dt is not None and not isinstance(dt, list) and hasattr(dt, 'name'):
        a["damage_type"] = [dt.name]
    elif isinstance(dt, list):
        a["damage_type"] = [t.name for t in dt if hasattr(t, 'name')]
    for k in ['damage', 'range', 'radius', 'hp_cost']:
        if hasattr(sp, k):
            try:
                v = sp.get_stat(k)
            except Exception:
                v = getattr(sp, k, 0)
            if isinstance(v, (int, float)) and not isinstance(v, bool) and v:
                a[k] = v
    try:
        cd = sp.get_stat('cool_down') if hasattr(sp, 'cool_down') else 0
    except Exception:
        cd = getattr(sp, 'cool_down', 0)
    if cd:
        a["cool_down"] = cd
    try:
        if sp.get_stat('quick_cast'):
            a["quick_cast"] = True
    except Exception:
        pass
    try:
        desc = sp.description or sp.get_description()
        a["desc"] = rtext(desc or "", fmt=sp.fmt_dict())
    except Exception:
        a["desc"] = ""
    # melee attacks (range<=1, no damage line) still note "melee"
    if getattr(sp, 'melee', False):
        a["melee"] = True
    return a

def _unit_passives(u):
    # The game's examine panel shows ALL buffs for a unit not in a level (our
    # case) — only filtering to BUFF_TYPE_PASSIVE for live units. So include
    # every buff that yields tooltip text; this captures innate behaviours like
    # regeneration, spawn generators, and "chance to become" transformations.
    out = []
    seen = set()
    for b in u.buffs:
        txt = ""
        try:
            fmt = b.fmt_dict() if hasattr(b, 'fmt_dict') else {}
            txt = rtext(b.get_tooltip() or "", fmt=fmt)
        except Exception:
            txt = ""
        if not txt and b.name and b.name != "Unnamed buff":
            txt = b.name
        if txt and txt not in seen:
            seen.add(txt)
            out.append(txt)
    return out

def register_unit(u):
    """Extract + store a unit's stat sheet; return its name."""
    name = u.name
    if name in UNITS:
        return name
    sheet = {
        "name": name,
        "hp": u.max_hp,
        "shields": getattr(u, 'shields', 0) or 0,
        "tags": [t.name for t in u.tags],
        "flying": bool(getattr(u, 'flying', False)),
        "stationary": bool(getattr(u, 'stationary', False)),
        "burrowing": bool(getattr(u, 'burrowing', False)),
        "radius": int(getattr(u, 'radius', 0) or 0),
        "is_boss": bool(getattr(u, 'is_boss', False)),
        "resists": {t.name: v for t, v in u.resists.items() if v},
        "abilities": [_unit_ability(sp) for sp in u.spells],
        "passives": _unit_passives(u),
        "refs": [],
        "icon": asset_filename(u.get_asset()),
    }
    cols, rows = sheet_grid(sheet["icon"], getattr(u, 'radius', 0))
    sheet["cols"] = cols     # idle-animation frame count (last row)
    sheet["rows"] = rows
    UNITS[name] = sheet
    return name

# ---------------------------------------------------------------------------
# Cross-references via static source analysis (AST)
# ---------------------------------------------------------------------------
# Instead of matching names in description prose (false positives), we read each
# class/factory's *source code* and find identifiers that are known game classes
# — e.g. Dread Lash's cast() contains `SealFate`, so it references Seal Fate.
import Monsters
import RareMonsters

FRAMEWORK_BASES = {'Spell', 'Equipment', 'Buff', 'Upgrade', 'Unit', 'Component', 'object'}
IDENT_MAP = {}     # python identifier -> (display_name, kind) ; value None == ambiguous
UNIT_FACTORY = {}  # unit display name -> its factory (for computing a unit's own refs)

def _register_factory(name, fac):
    if not name:
        return
    if name in UNIT_FACTORY and UNIT_FACTORY[name] is not fac:
        UNIT_FACTORY[name] = None    # ambiguous
    elif name not in UNIT_FACTORY:
        UNIT_FACTORY[name] = fac

def _register_ident(ident, name, kind):
    if not ident or not name:
        return
    cur = IDENT_MAP.get(ident, '__missing__')
    if cur == '__missing__':
        IDENT_MAP[ident] = (name, kind)
    elif cur is not None and cur != (name, kind):
        IDENT_MAP[ident] = None   # same identifier maps to >1 thing -> unusable

def build_ident_map(monster_factories):
    for cons in Spells.all_player_spell_constructors:
        try: _register_ident(cons.__name__, cons().name, 'spell')
        except Exception: pass
    for entry in Equipment.all_equipment:
        if isinstance(entry, type):
            try: _register_ident(entry.__name__, entry().name, 'equipment')
            except Exception: pass
    for fac in monster_factories:
        try: _register_ident(getattr(fac, '__name__', None), fac().name, 'unit')
        except Exception: pass
        _register_factory(getattr(_safe_call(fac), 'name', None), fac)
    # Also map every zero-arg unit factory in Monsters/RareMonsters (e.g.
    # BrainSapling, which only appears as a spawned minion) so code references
    # to them resolve. Refs to units without a card are pruned later.
    for mod in (Monsters, RareMonsters):
        for ident, obj in list(vars(mod).items()):
            if not callable(obj) or isinstance(obj, type):
                continue
            u = _safe_call(obj)
            if isinstance(u, Unit) and u.name:
                _register_ident(ident, u.name, 'unit')
                _register_factory(u.name, obj)

def _safe_call(fac):
    try:
        return fac()
    except Exception:
        return None

def _collect_idents(srcs):
    idents = set()
    for src in srcs:
        if not src:
            continue
        try:
            tree = ast.parse(textwrap.dedent(src))
        except (SyntaxError, ValueError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Name):
                idents.add(node.id)
            elif isinstance(node, ast.Attribute):
                idents.add(node.attr)
    return idents

_SRC_CACHE = {}
def _getsource(o):
    key = id(o)
    if key not in _SRC_CACHE:
        try:
            _SRC_CACHE[key] = inspect.getsource(o)
        except Exception:
            _SRC_CACHE[key] = None
    return _SRC_CACHE[key]

def refs_for(instance, entry, self_name):
    """Return [[display_name, kind], …] this entity references in its code."""
    srcs = [_getsource(entry)]                   # the registry entry (class / factory / lambda)
    cls = type(instance)
    if isinstance(cls, type):
        for base in cls.__mro__:                 # base-class method bodies (generic logic)
            if base is object or base.__name__ in FRAMEWORK_BASES:
                continue
            srcs.append(_getsource(base))
    out, seen = [], set()
    for ident in _collect_idents(srcs):
        m = IDENT_MAP.get(ident)
        if not m:
            continue
        name, kind = m
        if name == self_name or name in seen:
            continue
        seen.add(name)
        out.append([name, kind])
    out.sort()
    return out

# ---------------------------------------------------------------------------
# Full monster roster (bestiary): base spawns + evolutions + rare rosters
# ---------------------------------------------------------------------------

MONSTER_NAMES = set()   # names that belong to the bestiary
MONSTER_DEPTH = {}      # name -> earliest spawn depth (base monsters only)

def collect_monster_factories():
    factories = {}        # factory -> earliest depth (or None)
    for entry in Monsters.spawn_options:
        base, depth = entry[0], entry[1]
        factories.setdefault(base, depth)
        if factories[base] is None or (depth and depth < factories[base]):
            factories[base] = depth
        if len(entry) > 2 and entry[2]:
            factories.setdefault(entry[2], None)
    for list_name in ['MONSTER_PACKS', 'IDOLS', 'SUPER_SPAWNERS', 'SPECIAL_MONSTERS', 'WIZARDS', 'KAIJU']:
        L = getattr(RareMonsters, list_name, None) or []
        for entry in L:
            factories.setdefault(entry[0], None)
    return factories

def extract_monsters(factories):
    for fac, depth in factories.items():
        try:
            u = fac()
        except Exception as e:
            print("skip monster", getattr(fac, '__name__', fac), e)
            continue
        if not isinstance(u, Unit):
            continue
        register_unit(u)
        UNITS[u.name]["refs"] = refs_for(u, fac, u.name)   # factory is authoritative for monsters
        MONSTER_NAMES.add(u.name)
        if depth is not None:
            cur = MONSTER_DEPTH.get(u.name)
            MONSTER_DEPTH[u.name] = depth if cur is None else min(cur, depth)

def summons_of(obj):
    """Return list of distinct unit names this spell/equipment/component can summon."""
    names = []
    seen = set()

    def add(u):
        if isinstance(u, Unit) and u.name not in seen:
            seen.add(u.name)
            register_unit(u)
            names.append(u.name)

    fn = getattr(obj, 'get_extra_examine_tooltips', None)
    if fn:
        try:
            for t in fn():
                add(t)
        except Exception:
            pass
    gu = getattr(obj, 'get_unit', None)
    if gu:
        try:
            add(gu())
        except Exception:
            pass
    return names

# ---------------------------------------------------------------------------
# Spells
# ---------------------------------------------------------------------------
# Stat lines shown on a spell card. Mirrors the game's spell examine panel:
# the dedicated range/charges/hp_cost lines it draws first, then every TT_ATTRS
# attribute (the "Attributes:" section). Derived from TT_ATTRS so channel/minion
# stats (e.g. max_channel) can't silently drop off again as the game evolves.
SPELL_STAT_KEYS = ['range', 'max_charges', 'hp_cost'] + list(TT_ATTRS)

def extract_spells():
    out = []
    for cons in Spells.all_player_spell_constructors:
        s = cons()
        fmt = s.fmt_dict()
        stats = {}
        for k in SPELL_STAT_KEYS:
            if hasattr(s, k):
                v = s.get_stat(k)
                if isinstance(v, (int, float)) and not isinstance(v, bool) and v:
                    stats[k] = v
        dtypes = []
        dt = getattr(s, 'damage_type', None)
        if dt:
            if isinstance(dt, list):
                dtypes = [t.name for t in dt]
            else:
                dtypes = [dt.name]
        upgrades = []
        for u in s.spell_upgrades:
            # Game order: auto-generated stat lines first, then prose (some
            # upgrades, e.g. Relentless Cascade, are pure stat with no prose).
            prose = rtext(u.get_description() or "", fmt=u.fmt_dict())
            parts = upgrade_bonus_lines(u) + ([prose] if prose else [])
            upgrades.append({
                "name": u.name,
                "level": getattr(u, 'level', 0),
                "desc": "\n".join(parts),
            })
        mod_stats, use_stats = spell_stat_tags(s)
        out.append({
            "name": s.name,
            "level": s.level,
            "tags": [t.name for t in s.tags],
            "damage_type": dtypes,
            "stats": stats,
            "requires_los": bool(getattr(s, 'requires_los', True)),
            "melee": bool(getattr(s, 'melee', False)),
            "quick_cast": bool(getattr(s, 'quick_cast', False)),
            "desc": rtext(s.get_description() or "", fmt=fmt),
            "upgrades": upgrades,
            "summons": summons_of(s),
            "refs": refs_for(s, cons, s.name),
            "mod_stats": mod_stats,
            "use_stats": use_stats,
            "icon": asset_filename(s.get_asset()),
        })
    out.sort(key=lambda d: (d["level"], d["name"]))
    return out

# ---------------------------------------------------------------------------
# Equipment
# ---------------------------------------------------------------------------
def extract_equipment():
    out = []
    for cons in Equipment.all_equipment:
        try:
            e = cons()
        except Exception as ex:
            print("skip equipment", cons, ex)
            continue
        recipe = []
        for tag, amt in getattr(e, 'recipe', []):
            recipe.append([tag.name, int(amt)])
        desc = rtext(e.get_description() or "", fmt=e.fmt_dict())
        bonus_lines = render_bonus_lines(e)
        mod_stats, use_stats = equipment_stat_tags(e)
        out.append({
            "name": e.name,
            "slot": SLOT_NAMES.get(getattr(e, 'slot', 0), "Trinket"),
            "tags": [t.name for t in e.tags],
            "recipe": recipe,
            "recipe_cost": sum(a for _, a in recipe),
            "desc": desc,
            "bonuses": bonus_lines,
            "summons": summons_of(e),
            "refs": refs_for(e, cons, e.name),
            "mod_stats": mod_stats,
            "use_stats": use_stats,
            "icon": asset_filename(e.get_asset()),
        })
    out.sort(key=lambda d: (d["recipe_cost"], d["name"]))
    return out

# ---------------------------------------------------------------------------
# Components
# ---------------------------------------------------------------------------
def extract_components():
    out = []
    tier_of = {}
    for c in Components.t1_components: tier_of[c] = 1
    for c in Components.t2_components: tier_of[c] = 2
    for c in Components.t3_components: tier_of[c] = 3
    seen = []
    pools = [("normal", Components.all_components), ("rare", Components.rare_components)]
    for pool_name, pool in pools:
        for cons in pool:
            c = cons()
            tier = tier_of.get(cons, len(c.tags))
            has_craft = type(c).on_craft is not ComponentBase.on_craft
            has_pickup = type(c).on_pickup is not ComponentBase.on_pickup
            out.append({
                "name": c.name,
                "tags": [t.name for t in c.tags],
                "tier": tier,
                "rare": bool(getattr(c, 'is_rare', False)) or pool_name == "rare",
                "pool": pool_name,
                "on_craft": has_craft,
                "on_pickup": has_pickup,
                "desc": rtext(getattr(c, 'description', "") or "", fmt={}),
                "summons": summons_of(c),
                "refs": refs_for(c, cons, c.name),
                "icon": asset_filename(c.get_asset()),
            })
    out.sort(key=lambda d: (d["tier"], d["name"]))
    return out

# ---------------------------------------------------------------------------
# Tags metadata
# ---------------------------------------------------------------------------
def extract_tags():
    # component_tags are the craftable/recipe tags
    comp_tags = [t.name for t in Components.component_tags]
    tags = {}
    for tag in Tags:
        tags[tag.name] = {"color": to_tup(tag.color)}
    # Single-letter essence codes shown in the crafting UI. The game derives them
    # from the tag-filter hotkeys (RiftWizard3.KEY_BIND_DEFS); mirrored here (UI
    # module isn't imported — same reason tooltip_colors are mirrored). Distinct
    # letters resolve first-letter clashes (Eye=Y, Dragon=R, Chaos=K, Slime=Z,
    # Ritual=U, Any=∗). Keep in sync with TAG_ABBR in app.js.
    tag_abbr = {
        "Any": "∗", "Fire": "F", "Ice": "I", "Lightning": "L", "Nature": "N",
        "Arcane": "A", "Dark": "D", "Holy": "H", "Metallic": "M", "Blood": "B",
        "Sorcery": "S", "Enchantment": "E", "Conjuration": "C", "Eye": "Y",
        "Dragon": "R", "Orb": "O", "Chaos": "K", "Slime": "Z", "Word": "W",
        "Translocation": "T", "Ritual": "U",
    }
    for name, ab in tag_abbr.items():
        if name in tags:
            tags[name]["abbr"] = ab
    return {"all": tags, "component_tags": comp_tags}

def main():
    monster_factories = collect_monster_factories()
    build_ident_map(monster_factories.keys())   # must precede any refs_for() call
    spells = extract_spells()
    equipment = extract_equipment()
    components = extract_components()            # these populate UNITS via summons_of()
    extract_monsters(monster_factories)         # full bestiary into UNITS
    # annotate units with monster-roster metadata + factory-derived refs
    for name, sheet in UNITS.items():
        sheet["is_monster"] = name in MONSTER_NAMES
        if name in MONSTER_DEPTH:
            sheet["depth"] = MONSTER_DEPTH[name]
        fac = UNIT_FACTORY.get(name)
        if fac:
            inst = _safe_call(fac)
            if inst is not None:
                sheet["refs"] = refs_for(inst, fac, name)
    # Prune cross-refs whose target has no card (e.g. units that are never
    # surfaced), so every link resolves to a real entry.
    valid = {'spell': {s['name'] for s in spells},
             'equipment': {e['name'] for e in equipment},
             'unit': set(UNITS.keys())}
    def prune(refs):
        return [r for r in refs if r[0] in valid.get(r[1], ())]
    for s in spells: s['refs'] = prune(s['refs'])
    for e in equipment: e['refs'] = prune(e['refs'])
    for c in components: c['refs'] = prune(c['refs'])
    for sheet in UNITS.values(): sheet['refs'] = prune(sheet['refs'])
    # Stable integer ids for shareable build URLs (append-only; see ids.py).
    # Mutates ids.json on disk — it MUST be committed alongside data.json.
    idmap = ids_mod.load_ids()
    ids_mod.assign(idmap, "equipment", [e["name"] for e in equipment])
    ids_mod.assign(idmap, "spell", [s["name"] for s in spells])
    ids_mod.assign_sp(idmap, spells)   # combined spell+upgrade ids (Guide SP track)
    ids_mod.save_ids(idmap)
    for e in equipment: e["id"] = idmap["equipment"][e["name"]]
    for s in spells: s["id"] = idmap["spell"][s["name"]]
    data = {
        "spells": spells,
        "equipment": equipment,
        "components": components,
        "units": UNITS,
        "tags": extract_tags(),
        "colors": tooltip_colors,
        "slots": list(SLOT_NAMES.values()),
        "stat_meta": {k: format_attr(k) for k in STAT_KEYS},
        "generated": __import__("datetime").date.today().isoformat(),
    }
    out_path = os.path.join(OUT_DIR, "data.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
    monsters = sum(1 for s in UNITS.values() if s.get("is_monster"))
    print("Wrote", out_path)
    print("spells:", len(data["spells"]), "equipment:", len(data["equipment"]),
          "components:", len(data["components"]), "units:", len(data["units"]),
          "(monsters:", monsters, ")")

if __name__ == "__main__":
    main()
